### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by pamarthisai** [Niceural/flash-loan-arbitrage-bot#1]
hi greate work but how to execute this pls add readme commands

**Comment by Niceural** [comment]
Hi, this project is not finished yet but I will add a description :)

**Comment by pamarthisai** [comment]
Thank u

**Comment by Niceural** [comment]
I've added a README with the installation steps. I'll be working on this project for at least a couple of weeks. Let me know if there's anything else you'd like to know. If you're working on a similar project and would like to collaborate, lmk as well :)
